---
default: &default
  adapter: postgresql
  host: <%= ENV['POSTGRES_HOST'] %>
  database: <%= ENV.fetch('POSTGRES_DATABASE') { 'foreman' } %>
  username: <%= ENV.fetch('POSTGRES_USERNAME') { 'foreman' } %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default

production:
  <<: *default