jruby-puppet: {
  ruby-load-path: [
    /opt/puppetlabs/puppet/lib/ruby/vendor_ruby,
  ]

  gem-home: /opt/puppetlabs/server/data/puppetserver/jruby-gems
  
  gem-path: [${jruby-puppet.gem-home}, "/opt/puppetlabs/server/data/puppetserver/vendored-jruby-gems", "/opt/puppetlabs/puppet/lib/ruby/vendor_gems"]

  master-conf-dir: /etc/puppetlabs/puppet

  master-code-dir: /etc/puppetlabs/code

  master-var-dir: /opt/puppetlabs/server/data/puppetserver

  master-run-dir: /var/run/puppetlabs/puppetserver

  master-log-dir: ${LOGDIR}

  max-active-instances: ${PUPPETSERVER_MAX_ACTIVE_INSTANCES}

  max-requests-per-instance: ${PUPPETSERVER_MAX_REQUESTS_PER_INSTANCE}
}

http-client: {
}

bolt: {
  projects-dir: "/etc/puppetlabs/code/projects"
}

profiler: {
  enabled: false
}

dropsonde: {
  enabled: false
}

