---
default: &default
  adapter: postgresql
  host: <%= ENV.fetch('POSTGRES_HOST') { 'localhost' } %>
  database: <%= ENV.fetch('POSTGRES_DATABASE') { 'foreman' } %>
  username: <%= ENV.fetch('POSTGRES_USERNAME') { 'foreman' } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { File.read('/etc/foreman/postgres_password') } %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default

production:
  <<: *default